#!/bin/bash

# ArchCosta Update Notifier

source /usr/share/archcosta/scripts/archcosta-script-lib-yad || exit 1

CheckUpdates() {
    local updates=$(checkupdates 2>/dev/null | wc -l)
    if [ "$updates" -gt 0 ]; then
        notify-send -i archcosta-logo "System Updates" "$updates updates available!"
    fi
}

Main() {
    CheckUpdates
}

Main "$@"
