#!/bin/bash
# /usr/lib/archcosta/lite-mode
# Disables compositor for systems with < 1 GB RAM

RAM_MB=$(free -m | awk '/Mem:/{print $2}')
if [ "$RAM_MB" -lt 1024 ]; then
    xfconf-query -c xfwm4 -p /general/use_compositing -s false
    xfconf-query -c xfce4-session -p /compat/LaunchGNOME -s false
    notify-send "ArchCosta" "Lite mode: compositor disabled for low RAM." -i archcosta
fi