# Memory
vm.swappiness = 10
vm.vfs_cache_pressure = 50
vm.dirty_ratio = 10
vm.dirty_background_ratio = 3
vm.max_map_count = 2147483642

# Kernel scheduler
kernel.sched_autogroup_enabled = 1
kernel.nmi_watchdog = 0
kernel.numa_balancing = 0
kernel.panic = 10

# Network
net.core.somaxconn = 8192
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_max_tw_buckets = 2000000
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 10
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_keepalive_time = 60
net.ipv4.tcp_keepalive_intvl = 10
net.ipv4.tcp_keepalive_probes = 6

# Security / Performance balance
kernel.kptr_restrict = 0
kernel.perf_event_paranoid = 1

# Filesystem
fs.file-max = 2097152
fs.inotify.max_user_watches = 524288