#!/bin/bash

# bspwm config for ArchCosta

# Border colors (Dracula)
BSPC=#282a36
BSPA=#6272a4
BSPO=#bd93f9

# Global settings
bspc config border_width 2
bspc config window_gap 8
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config click_on_modifier false
bspc config ignore_ewmh_focus true

# Colors
bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#bd93f9"
bspc config presel_border_color "#ff79c6"
bspc config urgent_border_color "#ff5555"

# External rules
bspc rule -a Zathura state=tiled
bspc rule -a mpv state=floating
bspc rule -a Gimp state=floating
bspc rule -a Firefox desktop='^2'
bspc rule -a Discord desktop='^6'
bspc rule -a Spotify desktop='^6'

# Auto-start
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
picom -f &
nitrogen --restore &
nm-applet &
xfce4-power-manager &
volumeicon &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dex --autostart --environment bspwm &
